# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-03-29 07:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stockapp', '0007_auto_20180201_1432'),
    ]

    operations = [
        migrations.CreateModel(
            name='BOSStock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.IntegerField(choices=[(b'0', b'Buy'), (b'1', b'Sell')], default=0, verbose_name=b'\xe4\xb9\xb0\xe5\x8d\x96\xe7\xb1\xbb\xe5\x9e\x8b')),
                ('number', models.IntegerField(verbose_name=b'\xe8\x82\xa1\xe7\xa5\xa8\xe7\xbc\x96\xe7\xa0\x81')),
                ('amount', models.IntegerField(default=100, verbose_name=b'\xe4\xb9\xb0\xe5\x8d\x96\xe6\x95\xb0\xe9\x87\x8f')),
                ('totles', models.FloatField(verbose_name=b'\xe6\x8c\x82\xe5\x8d\x95\xe9\x87\x91\xe9\xa2\x9d')),
                ('ntotle', models.FloatField(verbose_name=b'\xe5\xbd\x93\xe5\x89\x8d\xe9\x87\x91\xe9\xa2\x9d')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name=b'\xe6\x8c\x82\xe5\x8d\x95\xe6\x97\xb6\xe9\x97\xb4')),
                ('state', models.IntegerField(choices=[(b'0', b'deity'), (b'1', b'deal'), (b'2', b'delete')], default=0, verbose_name=b'\xe7\x8a\xb6\xe6\x80\x81')),
            ],
            options={
                'ordering': ['id'],
                'verbose_name': '\u4e70\u5356\u6302\u5355',
                'verbose_name_plural': '\u4e70\u5356\u6302\u5355',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='frozen_money',
            field=models.FloatField(blank=True, null=True, unique=True, verbose_name=b'\xe5\x86\xbb\xe7\xbb\x93\xe8\xb5\x84\xe9\x87\x91'),
        ),
        migrations.AddField(
            model_name='bosstock',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
