# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-03-29 07:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockapp', '0008_auto_20180329_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='money',
            field=models.FloatField(blank=True, null=True, verbose_name=b'\xe8\xb5\x84\xe9\x87\x91'),
        ),
    ]
