# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-08-05 11:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockapp', '0010_auto_20180403_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bosstock',
            name='genre',
            field=models.IntegerField(choices=[(0, b'Buy'), (1, b'Sell')], default=0, verbose_name=b'\xe4\xb9\xb0\xe5\x8d\x96\xe7\xb1\xbb\xe5\x9e\x8b'),
        ),
        migrations.AlterField(
            model_name='bosstock',
            name='state',
            field=models.IntegerField(choices=[(0, b'deity'), (1, b'deal'), (2, b'delete'), (3, b'cancel')], default=0, verbose_name=b'\xe7\x8a\xb6\xe6\x80\x81'),
        ),
    ]
